[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# Uncomment this option to make `cargo run` flash your code using `probe-run`
# from knurling-rs.
# runner = "probe-run --chip STM32H743VITx"

rustflags = [
  # LLD (shipped with the Rust toolchain) is used as the default linker
  "-C", "link-arg=-Tlink.x",
  # Include the defmt.x linker script from knurling-rs.
  #"-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)

[alias]
hr = "objcopy --features=matekf411 --target thumbv7m-none-eabi -- -O ihex app.hex"
bm = "build --features=matekh743 --target thumbv7em-none-eabihf"
